sudo: required
services:
  - docker

before_install:
  - docker build -t rafa/docker-react -f Dockerfile.prod .

script:
  - docker run rafa/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'ap-southeast-2'
  app: 'docker-react'
  env: 'DockerReact-env'
  bucket_name: 'elasticbeanstalk-ap-southeast-2-383910874237'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: '$AWS_SECRET_KEY'
